#!/bin/sh
# Operating systems - project01
# author: sabina gulcikova
#        <xgulci00@stud.fit.vutbr.cz>
# date: 15/03/20
POSIXLY_CORRECT=yes

DIR=$(pwd)
ND=0
NF=0
#parsovanie argumentov
#prechadzanie suborov
#normalizacia
#ignorovanie suborov

echo "Root directory: $DIR"
echo "Directiories: $ND"
echo "All files: $NF"
echo "File size histogram:"
